AWSTemplateFormatVersion: 2010-09-09
Description: |
  
Parameters:
  
Metadata:
  
Mappings:
  
Conditions:
  
Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private | PublicRead | PublicReadWrite | AuthenticatedRead | LogDeliveryWrite | BucketOwnerRead | BucketOwnerFullControl
      BucketName: 
      CorsConfiguration: 
      LifecycleConfiguration: 
      NotificationConfiguration: 
      VersioningConfiguration: 
      WebsiteConfiguration: 
      Tags:
        - Key: key
          Value: value
  lambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: 
      FunctionName: 
      Handler: 
      KmsKeyArn: 
      MemorySize: 128
      Role: role-arn
      Runtime: nodejs | nodejs4.3 | nodejs6.10 | nodejs8.10 | java8 | python2.7 | python3.6 | dotnetcore1.0 | dotnetcore2.0 | dotnetcore2.1 | nodejs4.3-edge | go1.x
      Timeout: 
      VpcConfig:
        SecurityGroupIds:
          - sg-id
        SubnetIds:
          - subnet-id
      Environment:
        Variables:
          key1: value1 # A map of key-value pairs that the Lambda function can access
      Code:
        S3Bucket: 
        S3Key: 
        S3ObjectVersion: 
        ZipFile: 
      Tags:
        - Key: keyname
          Value: value
Transform:
  
Outputs: