---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template deploys an S3 Bucket with encryption

Parameters:

  pProjectName:
    Description: Nombre del proyecto.
    Type: String

Resources:

  rBucketArchivosPrerequisitosInfra:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: Private
        BucketName: !Ref 'AWS::StackName'
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: "AES256"
        VersioningConfiguration:
          Status: Enabled
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        Tags:
          - Key: "bancolombia:clasificacion-confidencialidad"
            Value: "confidencial"
          - Key: "bancolombia:clasificacion-integridad"
            Value: "impacto critico"
          - Key: "bancolombia:clasificacion-disponibilidad"
            Value: "impacto critico"
          - Key: "bancolombia:dominio-informacion"
            Value: "productos-financiera-contable-legal-riesgos-seguridad"
          - Key: "bancolombia:datos-personales"
            Value: "clientes-empleados"
          - Key: "bancolombia:cumplimiento"
            Value: "sox-bia"
          - Key: Name
            Value: !Join ["", [Ref: "AWS::StackName"]]

  rS3PolicyArchivosPrerequisitosInfra:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref rBucketArchivosPrerequisitosInfra
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Join ["", [ 'arn:aws:iam::', !Ref AWS::AccountId , ':root']]
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:GetObjectACL
              - s3:PutObjectACL
            Resource:
              - !Join ['', ['arn:aws:s3:::', !Ref 'rBucketArchivosPrerequisitosInfra', /*]]
              - !Join ['', ['arn:aws:s3:::', !Ref 'rBucketArchivosPrerequisitosInfra']]
              # - !Join ['', ['arn:aws:s3:::', !Ref 'rBucketArchivosPrerequisitosInfra']]
  #         - Effect: Allow
  #           Principal:
  #             AWS: !Ref pS3SFTPRol
  #           Action:
  #             - s3:ListBucket
  #             - s3:GetBucketLocation
  #        Resource: !Join ['', ['arn:aws:s3:::', !Ref 'rBucketArchivosPrerequisitosInfra']]
