AWSTemplateFormatVersion: 2010-09-09
Description: This template deploys an Amazon RDS for Oracle instance

Parameters:

  pAmbiente:
    Description: Ambiente AWS
    Type: String

  pAmbienteMurex:
    Description: Ambiente Murex
    Type: String

  pApplicationCode:
    Description: Código Murex
    Type: String

  pProjectName:
    Description: Nombre del Proyecto
    Type: String

  pKMSKeyId:
    Description: The ARN of the AWS Key Management Service (AWS KMS)
    Type : AWS::SSM::Parameter::Value<String>

  pUserMX:
    Description: Usuario Murex
    Type: String

  pPasswdMX:
    Description: Password Murex
    Type: String
    NoEcho: true

  pUserDM:
    Description: Usuario Datamart
    Type: String

  pPasswdDM:
    Description: Password Datamart
    Type: String
    NoEcho: true

  pUserLimits:
    Description: Usuario MLC
    Type: String

  pPasswdLimits:
    Description: Password MLC
    Type: String
    NoEcho: true

  pUserSchfonpet:
    Description: Usuario Pfico y Carteras Colectivas
    Type: String

  pPasswdSchfonpet:
    Description: Password Pfico y Carteras Colectivas
    Type: String
    NoEcho: true

  pUserModfincon:
    Description: Usuario Modulo Financiero Contable
    Type: String

  pPasswdModfincon:
    Description: Password Modulo Financiero Contable
    Type: String
    NoEcho: true

  pUserSchc016:
    Description: Usuario Circular 016
    Type: String

  pPasswdSchc016:
    Description: Password Circular 016
    Type: String
    NoEcho: true

  pUserUsrint:
    Description: Usuario Interfaces Batch
    Type: String

  pPasswdUsrint:
    Description: Usuario Interfaces Batch
    Type: String
    NoEcho: true

  pUserModimpyval:
    Description: Usuario Modulo Impuestos
    Type: String

  pPasswdModimpyval:
    Description: Password Modulo Impuestos
    Type: String
    NoEcho: true

  pUserDatical:
    Description: Usuario Conexion Datical
    Type: String

  pPasswdDatical:
    Description: Password Conexion Datical
    Type: String
    NoEcho: true

  pSchemaDatical:
    Description: Usuario Esquema Datical
    Type: String

  pPasswdSchemaDatical:
    Description: Password Esquema Datical
    Type: String
    NoEcho: true

  pUserModval:
    Description: Usuario Modulo de Valoracion Banco
    Type: String

  pPasswdModval:
    Description: Password Modulo de Valoracion Banco
    Type: String
    NoEcho: true

  pUserSchimpBA:
    Description: Usuario de Valoracion Banistmo
    Type: String

  pPasswdSchimpBA:
    Description: Password de Valoracion Banistmo
    Type: String
    NoEcho: true

  pUserModvarreg2:
    Description: Usuario Valoracion Regulatoria Fiduciaria
    Type: String

  pPasswdModvarreg2:
    Description: Password Valoracion Regulatoria Fiduciaria
    Type: String
    NoEcho: true

  pUserModvarext:
    Description: Usuario Valoracion Crediticia
    Type: String

  pPasswdModvarext:
    Description: Password Valoracion Crediticia
    Type: String
    NoEcho: true

  pPort:
    Description: RDS port.
    Type: String

  pDNSHost:
    Description: RDS DNShost.
    Type: String

  pDBName:
    Description: Name of the DB instance.
    ConstraintDescription: >-
      Must begin with a letter and contain only
      alphanumeric characters.
    Type: String


Resources:

  rSecretMurexUser:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name:
        Fn::Join: ["-", [ Ref: "AWS::StackName" , "SecretUserMurex"]]
      Description: Secreto Usuario Murex
      KmsKeyId: !Ref pKMSKeyId
      SecretString: !Join ["", ["{\"username\":\"", !Ref pUserMX,"\",",
        "\"password\":\"", !Ref pPasswdMX,"\",",
        "\"host\":\"", !Ref pDNSHost ,"\",",
        "\"dbname\":\"", !Ref pDBName ,"\",",
        "\"puerto\":\"", !Ref pPort,"\"}"
        ]]

  rSecretMLCUser:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name:
        Fn::Join: ["-", [ Ref: "AWS::StackName" , "SecretUserMLC"]]
      Description: Secreto Usuario MLC
      KmsKeyId: !Ref pKMSKeyId
      SecretString: !Join ["", ["{\"username\":\"", !Ref pUserLimits,"\",",
        "\"password\":\"", !Ref pPasswdLimits,"\",",
        "\"host\":\"", !Ref pDNSHost ,"\",",
        "\"dbname\":\"", !Ref pDBName ,"\",",
        "\"puerto\":\"", !Ref pPort,"\"}"
        ]]

  rSecretDatamartUser:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name:
        Fn::Join: ["-", [ Ref: "AWS::StackName" , "SecretUserDatamart"]]
      Description: Secreto Usuario Datamart
      KmsKeyId: !Ref pKMSKeyId
      SecretString: !Join ["", ["{\"username\":\"", !Ref pUserDM,"\",",
        "\"password\":\"", !Ref pPasswdDM,"\",",
        "\"host\":\"", !Ref pDNSHost ,"\",",
        "\"dbname\":\"", !Ref pDBName ,"\",",
        "\"puerto\":\"", !Ref pPort,"\"}"
        ]]

  rSecretDaticalUser:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name:
        Fn::Join: ["-", [ !Ref pApplicationCode, !Ref pProjectName, !Ref pAmbiente, "secretrds-CNXDATIREF"]]
      Description: Secreto Usuario Conexion Datical
      KmsKeyId: !Ref pKMSKeyId
      SecretString: !Join ["", ["{\"username\":\"", !Ref pUserDatical,"\",",
        "\"password\":\"", !Ref pPasswdDatical,"\",",
        "\"host\":\"", !Ref pDNSHost ,"\",",
        "\"dbname\":\"", !Ref pDBName ,"\",",
        "\"puerto\":\"", !Ref pPort,"\"}"
        ]]

  rSecretDaticalSchema:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name:
        Fn::Join: ["-", [ !Ref pApplicationCode, !Ref pProjectName, !Ref pAmbiente, "secretrds-DATICALTRACKING"]]
      Description: Secreto Esquema Datical
      KmsKeyId: !Ref pKMSKeyId
      SecretString: !Join ["", ["{\"username\":\"", !Ref pSchemaDatical,"\",",
        "\"password\":\"", !Ref pPasswdSchemaDatical,"\",",
        "\"host\":\"", !Ref pDNSHost ,"\",",
        "\"dbname\":\"", !Ref pDBName ,"\",",
        "\"puerto\":\"", !Ref pPort,"\"}"
        ]]

  rSecretSchfonpetUser:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name:
        Fn::Join: ["-", [ Ref: "AWS::StackName" , "SecretUserPficoCarterasColectivas"]]
      Description: Secreto Usuario Pfico y Carteras Colectivas
      KmsKeyId: !Ref pKMSKeyId
      SecretString: !Join ["", ["{\"username\":\"", !Ref pUserSchfonpet,"\",",
        "\"password\":\"", !Ref pPasswdSchfonpet,"\",",
        "\"host\":\"", !Ref pDNSHost ,"\",",
        "\"dbname\":\"", !Ref pDBName ,"\",",
        "\"puerto\":\"", !Ref pPort,"\"}"
        ]]

  rSecretModfinconUser:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name:
        Fn::Join: ["-", [ Ref: "AWS::StackName" , "SecretUserModuloFinancieroContable"]]
      Description: Secreto Usuario Modulo Financiero Contable
      KmsKeyId: !Ref pKMSKeyId
      SecretString: !Join ["", ["{\"username\":\"", !Ref pUserModfincon,"\",",
        "\"password\":\"", !Ref pPasswdModfincon,"\",",
        "\"host\":\"", !Ref pDNSHost ,"\",",
        "\"dbname\":\"", !Ref pDBName ,"\",",
        "\"puerto\":\"", !Ref pPort,"\"}"
        ]]

  rSecretSchc016User:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name:
        Fn::Join: ["-", [ Ref: "AWS::StackName" , "SecretUserCircular016"]]
      Description: Secreto Usuario Circular 016
      KmsKeyId: !Ref pKMSKeyId
      SecretString: !Join ["", ["{\"username\":\"", !Ref pUserSchc016,"\",",
        "\"password\":\"", !Ref pPasswdSchc016,"\",",
        "\"host\":\"", !Ref pDNSHost ,"\",",
        "\"dbname\":\"", !Ref pDBName ,"\",",
        "\"puerto\":\"", !Ref pPort,"\"}"
        ]]

  rSecretUsrintUser:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name:
        Fn::Join: ["-", [ Ref: "AWS::StackName" , "SecretUserInterfacesBatch"]]
      Description: Secreto Usuario Interfaces Batch
      KmsKeyId: !Ref pKMSKeyId
      SecretString: !Join ["", ["{\"username\":\"", !Ref pUserUsrint,"\",",
        "\"password\":\"", !Ref pPasswdUsrint,"\",",
        "\"host\":\"", !Ref pDNSHost ,"\",",
        "\"dbname\":\"", !Ref pDBName ,"\",",
        "\"puerto\":\"", !Ref pPort,"\"}"
        ]]

  rSecretModimpyvalUser:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name:
        Fn::Join: ["-", [ Ref: "AWS::StackName" , "SecretUserModuloImpuestos"]]
      Description: Secreto Usuario Modulo Impuestos
      KmsKeyId: !Ref pKMSKeyId
      SecretString: !Join ["", ["{\"username\":\"", !Ref pUserModimpyval,"\",",
        "\"password\":\"", !Ref pPasswdModimpyval,"\",",
        "\"host\":\"", !Ref pDNSHost ,"\",",
        "\"dbname\":\"", !Ref pDBName ,"\",",
        "\"puerto\":\"", !Ref pPort,"\"}"
        ]]

  rSecretdModvarextUser:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name:
        Fn::Join: ["-", [ Ref: "AWS::StackName" , "SecretUserModuloValoracionCrediticia"]]
      Description: Secreto Usuario Modulo Valoracion Crediticia
      KmsKeyId: !Ref pKMSKeyId
      SecretString: !Join ["", ["{\"username\":\"", !Ref pUserModvarext,"\",",
        "\"password\":\"", !Ref pPasswdModvarext,"\",",
        "\"host\":\"", !Ref pDNSHost ,"\",",
        "\"dbname\":\"", !Ref pDBName ,"\",",
        "\"puerto\":\"", !Ref pPort,"\"}"
        ]]

  rSecretModvarreg2User:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name:
        Fn::Join: ["-", [ Ref: "AWS::StackName" , "SecretUserModuloValoracionFiduciaria"]]
      Description: Secreto Usuario Modulo Valoracion Fiduciaria
      KmsKeyId: !Ref pKMSKeyId
      SecretString: !Join ["", ["{\"username\":\"", !Ref pUserModvarreg2,"\",",
        "\"password\":\"", !Ref pPasswdModvarreg2,"\",",
        "\"host\":\"", !Ref pDNSHost ,"\",",
        "\"dbname\":\"", !Ref pDBName ,"\",",
        "\"puerto\":\"", !Ref pPort,"\"}"
        ]]

  rSecretSchimpBAUser:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name:
        Fn::Join: ["-", [ Ref: "AWS::StackName" , "SecretUserModuloValoracionBanistmo"]]
      Description: Secreto Usuario Valoracion Banistmo
      KmsKeyId: !Ref pKMSKeyId
      SecretString: !Join ["", ["{\"username\":\"", !Ref pUserSchimpBA,"\",",
        "\"password\":\"", !Ref pPasswdSchimpBA,"\",",
        "\"host\":\"", !Ref pDNSHost ,"\",",
        "\"dbname\":\"", !Ref pDBName ,"\",",
        "\"puerto\":\"", !Ref pPort,"\"}"
        ]]

  rSecretModvalUser:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name:
        Fn::Join: ["-", [ Ref: "AWS::StackName" , "SecretUserValoracionBanco"]]
      Description: Secreto Valoracion Banco
      KmsKeyId: !Ref pKMSKeyId
      SecretString: !Join ["", ["{\"username\":\"", !Ref pUserModval,"\",",
        "\"password\":\"", !Ref pPasswdModval,"\",",
        "\"host\":\"", !Ref pDNSHost ,"\",",
        "\"dbname\":\"", !Ref pDBName ,"\",",
        "\"puerto\":\"", !Ref pPort,"\"}"
        ]]