AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template para la creacion del

Parameters:

  pBucketTransversal:
    Description: BucketTransversal
    Type: String

  pIdSftpServer:
    Description: Id del servidor de transfer
    Type: String

  pSSHKey:
    Description: Llave publica del usuario de transfer
    Type: String

  pImportBase:
    Description: The base name of the imported objetcs
    Type: String

  pKMSKeyArnTransversal:
    Description: The ARN of the AWS Key Management Service (AWS KMS)
    Type: String

Resources:

  sftpRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service: transfer.amazonaws.com
            Action:
              - "sts:AssumeRole"
      RoleName: !Join [ "-", [!Ref pImportBase, s3, sftp, rol] ]

  sftpPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Join [ "-", [!Ref pImportBase, s3, sftp, policy] ]
      Roles:
      - !Ref sftpRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: [
                      "s3:ListBucket",
                      "s3:GetBucketLocation"]
            Resource: !Join [ ":", [ arn, aws, 's3::', !Ref pBucketTransversal]]
          - Effect: "Allow"
            Action: [
                      "s3:PutObject",
                      "s3:GetObject",
                      "s3:DeleteObjectVersion",
                      "s3:DeleteObject",
                      "s3:GetObjectVersion",
                      "s3:GetObjectACL",
                      "s3:PutObjectACL"]
            Resource: !Join [ "", [ 'arn:aws:s3:::', !Ref pBucketTransversal, '/*']]
          - Effect: "Allow"
            Action:
              - "kms:Encrypt"
              - "kms:Decrypt"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:DescribeKey"
            Resource: !Ref pKMSKeyArnTransversal
          - Effect: "Allow"
            Action:
              - "kms:CreateGrant"
              - "kms:ListGrants"
              - "kms:RevokeGrant"
            Resource: !Ref pKMSKeyArnTransversal
            Condition:
                Bool:
                  kms:GrantIsForAWSResource: true

  TransferUser:
    Type: AWS::Transfer::User
    Properties:
      HomeDirectory: !Join ['', ["/", Ref: pBucketTransversal]]
      Role: !GetAtt sftpRole.Arn
      ServerId: !Ref pIdSftpServer
      SshPublicKeys:
        - !Ref pSSHKey
      UserName: !Join ["-", [!Ref 'AWS::StackName' ,'user'] ]

Outputs:

  rolArn:
    Description : ARN del rol creado para el consumo del Bucket
    Value: !GetAtt sftpRole.Arn
