AWSTemplateFormatVersion: '2010-09-09'
Description: ' Windows temporal para CSR '

############################## Parameters ####################################################
Parameters:

  pApplicationCode:
    Description: Codigo de la aplicacion.
    Type: String
    Default: 

  pCostCenter:
    Description: Centro Costos del proyecto.
    Type: String
    Default: c103500155

  pPMO:
    Description: Pmo de proyecto
    Type: String
    Default: pmo30686

  pBussiness: 
    Description: Unidad de Negocio de la de la aplicacion.
    Type: String
    Default: 

  pProjectName:
    Description: Nombre del proyecto.
    Type: String
    Default: 

  pEnvironment:
    Type: String
    Description: Environment of Solution
    Default: 

  pInstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: 

  pImageId:
    Description: EC2 Instance AMI
    Type: AWS::EC2::Image::Id
    Default: 

  pInstanceVpcId:
    Description: The VPC of the worker instances
    Type: AWS::EC2::VPC::Id
    Default: 

  pInstanceSubnet:
    Description: The subnets where workers can be created.
    Type: AWS::EC2::Subnet::Id
    Default: 

  pBucketCsr:
    Type: String
    Description: The S3 bucket name that contains the certificate.
    Default: 


Resources:
######################### Resources EC2#############################
  rEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "false"
          DeviceIndex: "0"
          GroupSet: 
            - Ref: rInstanceSecurityGroup
          SubnetId: 
            Ref: pInstanceSubnet
      InstanceType: !Ref pInstanceType
      ImageId: !Ref pImageId
      IamInstanceProfile: !Ref rInstanceProfile
      UserData:
        Fn::Base64:
          Fn::Sub:
          - |
            <powershell>



            </powershell>
            
          - dcmbucketl: !Ref pBucketCsr
            ambiente: !Ref pEnvironment

      Tags:
        -
          Key: bancolombia:application-code
          Value: !Ref pApplicationCode
        -
          Key: bancolombia:project-name	
          Value: !Ref pProjectName
        -
          Key: bancolombia:environment
          Value: !Ref pEnvironment
        -
          Key: bancolombia:cost-center	
          Value: !Ref pCostCenter
        -
          Key: bancolombia:pmo
          Value: !Ref pPMO
        -
          Key: bancolombia:business-service	
          Value: !Ref pBussiness
        -
          Key: Name
          Value: !Join ["-", [!Ref pApplicationCode, !Ref pProjectName, !Ref pEnvironment, ec2-request]] 
           

  rInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles: [!Ref rec2Role]
      
  rec2PolicyS3:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: EC2-s3-policy
      Roles:
      - !Ref rec2Role
      PolicyDocument:
        Version: '2012-10-17'
        Statement: 
          - 
            Effect: "Allow"
            Action: [

                    ]
            Resource: "ARD DEL S3"



  rInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join ["-", [!Ref pApplicationCode, !Ref pProjectName, !Ref pEnvironment, sg-request]]
      GroupDescription: Allow conection to client
      VpcId:
        Ref: pInstanceVpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: XX
        ToPort: XX
        CidrIp: X.X.X.X/X
      Tags:
        -
          Key: bancolombia:application-code
          Value: !Ref pApplicationCode
        -
          Key: bancolombia:project-name	
          Value: !Ref pProjectName
        -
          Key: bancolombia:environment
          Value: !Ref pEnvironment
        -
          Key: bancolombia:cost-center	
          Value: !Ref pCostCenter
        -
          Key: bancolombia:pmo
          Value: !Ref pPMO
        -
          Key: bancolombia:business-service	
          Value: !Ref pBussiness