---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template deploys an S3 Bucket with encryption


Parameters:

  pCostCenter:
    Description: Centro Costos del proyecto.
    Type: String
    Default: c103500025

  pBussiness:
    Description: Unidad de Negocio de la de la aplicacion.
    Type: String
    Default: tesoreria

  pPMO:
    Description: Pmo de proyecto
    Type: String
    Default: pmo30686

  pApplicationCode:
    Description: The application code
    Type: String
    Default: aw0434001

  pKMSKeyId:
    Description: The ARN of the AWS Key Management Service (AWS KMS)
    Type : AWS::SSM::Parameter::Value<String>
    Default: "/aw0434001/murex-core/dev/kms-arn-latest"

  pProjectName:
    Description: Name of the project
    Type: String
    Default: murex-core

  pEnvironment:
    Description: EFS de ambiente a desplegar
    Type: String
    AllowedValues:
        - dev
        - qa
        - pdn

  # pS3SFTPRol:
  #   Description: Nombre del rol para el transfersftp.
  #   Type: String
  #   Default: "arn:aws:iam::763669947983:role/aw0991001-murex-core-dev-s3-sftp-rol"

Resources:

  rBucketArchivos:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Join ["-", [!Ref 'AWS::StackName' , "archivos"]]
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                KMSMasterKeyID: !Ref pKMSKeyId
                SSEAlgorithm: "aws:kms"
        VersioningConfiguration:
          Status: Enabled
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        Tags:
          - Key: bancolombia:info-activos
            Value: "Si"
          - Key: bancolombia:clasificacion-confidencialidad
            Value: "Interna"
          - Key: bancolombia:clasificacion-integridad
            Value: "Impacto Tolerable"
          - Key: bancolombia:clasificacion-disponibilidad
            Value: "Impacto Tolerable"

  # rS3PolicyArchivos:
  #   Type: AWS::S3::BucketPolicy
  #   DependsOn: rBucketArchivos
  #   Properties:
  #     Bucket: !Ref rBucketArchivos
  #     PolicyDocument:
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             AWS: !Ref 'pS3SFTPRol'
  #           Action:
  #             - s3:PutObject
  #             - s3:GetObject
  #             - s3:GetObjectVersion
  #             - s3:GetObjectACL
  #             - s3:PutObjectACL
  #           Resource: !Join ['', ['arn:aws:s3:::', !Ref 'rBucketArchivos', /*]]
  #         - Effect: Allow
  #           Principal:
  #             AWS: !Ref pS3SFTPRol
  #           Action:
  #             - s3:ListBucket
  #             - s3:GetBucketLocation
  #           Resource: !Join ['', ['arn:aws:s3:::', !Ref 'rBucketArchivos']]