---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Creacion SG-Murex-Core

Parameters:

  pApplicationCode:
    Description: Codigo de la aplicacion.
    Type: String
    Default: aw0434001

  pCostCenter:
    Description: Centro Costos del proyecto.
    Type: String
    Default: c103500025

  pPMO:
    Description: Pmo de proyecto
    Type: String
    Default: pmo30686

  pBussiness:
    Description: Unidad de Negocio de la de la aplicacion.
    Type: String
    Default: tesoreria

  pProjectName:
    Description: Nombre del proyecto.
    Type: String
    Default: murex-core

  pDefaultVPC:
    Description: VPC donde debe quedar asociada la instancia
    Type: 'AWS::EC2::VPC::Id'

  pEnvironment:
    Description: Environment where it unfolds.
    Type: String
    Default: dev

  pPuertoRDS:
    Description: Puerto de la rds
    Type: String
    Default: 50000
  
  pPuertoEFS:
    Description: Puerto de la efs
    Type: String
    Default: 2049

Resources:
  rSecurityGroupEC2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access EC2
      VpcId:
        Ref: pDefaultVPC
      GroupName: !Join ["-", [ Ref: "AWS::StackName" , "ec2" ]]
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 10.0.0.0/8
          Description: "Permisos cliente murex"
      Tags:
      - Key: Name
        Value: !Join ["-", [ Ref: "AWS::StackName" , "ec2" ]]
      -
        Key: bancolombia:application-code
        Value: !Ref pApplicationCode
      -
        Key: bancolombia:project-name
        Value: !Ref pProjectName
      -
        Key: bancolombia:environment
        Value: !Ref pEnvironment
      -
        Key: bancolombia:cost-center
        Value: !Ref pCostCenter
      -
        Key: bancolombia:pmo
        Value: !Ref pPMO
      -
        Key: bancolombia:business-service
        Value: !Ref pBussiness

  rSecurityGroupRDS:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access RDS
      VpcId:
        Ref: pDefaultVPC
      GroupName: !Join ["-", [ Ref: "AWS::StackName" , "rds" ]]
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 
            Ref: pPuertoRDS
          ToPort: 
            Ref: pPuertoRDS
          SourceSecurityGroupId:
            Ref: rSecurityGroupEC2
          Description: "Acceso EC2 to RDS"
      Tags:
      - Key: Name
        Value: !Join ["-", [ Ref: "AWS::StackName" , "rds" ]]
      -
        Key: bancolombia:application-code
        Value: !Ref pApplicationCode
      -
        Key: bancolombia:project-name
        Value: !Ref pProjectName
      -
        Key: bancolombia:environment
        Value: !Ref pEnvironment
      -
        Key: bancolombia:cost-center
        Value: !Ref pCostCenter
      -
        Key: bancolombia:pmo
        Value: !Ref pPMO
      -
        Key: bancolombia:business-service
        Value: !Ref pBussiness



  rSecurityGroupEFS:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access EFS
      VpcId:
        Ref: pDefaultVPC
      GroupName: !Join ["-", [ Ref: "AWS::StackName" , "efs" ]]
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref pPuertoEFS
          ToPort: !Ref  pPuertoEFS
          SourceSecurityGroupId:
            Ref: rSecurityGroupEC2
          Description: "Acceso EC2 to EFS"
      Tags:
      - Key: Name
        Value: !Join ["-", [ Ref: "AWS::StackName" , "efs" ]]
      -
        Key: bancolombia:application-code
        Value: !Ref pApplicationCode
      -
        Key: bancolombia:project-name
        Value: !Ref pProjectName
      -
        Key: bancolombia:environment
        Value: !Ref pEnvironment
      -
        Key: bancolombia:cost-center
        Value: !Ref pCostCenter
      -
        Key: bancolombia:pmo
        Value: !Ref pPMO
      -
        Key: bancolombia:business-service
        Value: !Ref pBussiness

Outputs:
  Message:
    Description: Mensaje
    Value: Los grupos de seguridad fueron creados
  rSecurityGroupRDS:
    Description: Id del SG de la RDS.
    Value:
      Ref: rSecurityGroupRDS
    Export:
      Name: !Join ["-", [ Ref: "AWS::StackName" , "rds" ]]
  rSecurityGroupEC2:
    Description: Id del SG de la EC2.
    Value:
      Ref: rSecurityGroupEC2
    Export:
      Name: !Join ["-", [ Ref: "AWS::StackName" , "ec2" ]]
  rSecurityGroupEFS:
    Description: Id del SG de la EFS.
    Value:
      Ref: rSecurityGroupEFS
    Export:
      Name: !Join ["-", [ Ref: "AWS::StackName" , "efs" ]]