AWSTemplateFormatVersion: 2010-09-09
Description: 'Crear ec2'

Parameters:
  pIdImage:
    Description: ID para usar en la instancia a desplegar
    Type: String

Resources:
  rEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref pIdImage
      # KeyName: cualquiercosa
      SecurityGroups: 
      - !Ref rInstanceSecurityGroup
      Tags:
        - Key: Name
          Value: EC2Alineacion   
      

  rInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh to client host
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0